package br.com.clinicaMed.enumeration;

public enum EspecialidadeMedica {
    ALERGIA_E_IMUNOLOGIA,
    CARDIOLOGIA,
    CLINICO_GERAL,
    DERMATOLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    NEUROLOGIA,
    OBSTETRICIA,
    OFTALMOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    REUMATOLOGIA,
    UROLOGIA
}
